{% set name = "texmaker" %}
{% set version = "5.1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://www.xm1math.net/texmaker/texmaker-{{ version }}.tar.bz2
  sha256: bfa52e5e0e3c61d5258ea8c69ea527f6bd20f0e23fe2da43b80aee00b2609f61

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - make  # [not win]
    - jom  # [win]
    - sed  # [not win]
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17  # [linux64]
    - {{ compiler('cxx') }}
    - {{ cdt('expat-devel') }}  # [linux]
    - {{ cdt('libxfixes-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxau') }}  # [linux]
    - {{ cdt('libxscrnsaver') }}  # [linux]
    - {{ cdt('libxscrnsaver-devel') }}  # [linux]    
  host:
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - xorg-libxfixes  # [linux]
    - qt
    - texlive-core  # [not win]
  run:

test:
  commands:
    - test -f $PREFIX/bin/texmaker  # [not win]
    - exist %PREFIX%/bin/texmaker  # [win]

about:
  home: https://www.xm1math.net/texmaker/
  license: GPL-2.0-only
  license_family: GPL2
  license_file: license.txt
  summary: Free cross-platform LaTeX editor

extra:
  recipe-maintainers:
    - izahn
