{% set name = "texmaker" %}
{% set version = "6.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://www.xm1math.net/texmaker/texmaker-{{ version }}.tar.bz2
  sha256: 977ce580e25c1ab6e0bc3da103be0b43ebf60b8ce0d27273104fdd7f586177fc
  patches:
    - 0001-fix-libgl.patch

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - make  # [not win]
    - jom  # [win]
    - sed  # [not win]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ cdt('expat-devel') }}  # [linux]
    - {{ cdt('libxfixes-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('libglvnd-glx') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxau') }}  # [linux]
    - {{ cdt('libxscrnsaver') }}  # [linux]
    - {{ cdt('libxscrnsaver-devel') }}  # [linux]    
  host:
    - xorg-libxfixes  # [linux]
    - qt-main
    - texlive-core  # [not win]
  run:
    - qt-main
    - texlive-core  # [not win]

test:
  commands:
    - test -f $PREFIX/bin/texmaker  # [not win]
    - exist %PREFIX%/bin/texmaker  # [win]

about:
  home: https://www.xm1math.net/texmaker/
  license: GPL-2.0-only
  license_family: GPL2
  license_file: license.txt
  summary: Free cross-platform LaTeX editor

extra:
  recipe-maintainers:
    - izahn
